// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contractsv1

import "time"

type ActionArtifact struct {
	// ApprovalState corresponds to the JSON schema field "approval_state".
	ApprovalState ActionArtifactApprovalState `json:"approval_state"`

	// ArtifactType corresponds to the JSON schema field "artifact_type".
	ArtifactType Identifier `json:"artifact_type"`

	// CampaignId corresponds to the JSON schema field "campaign_id".
	CampaignId Identifier `json:"campaign_id"`

	// Content corresponds to the JSON schema field "content".
	Content interface{} `json:"content"`

	// ContentSha256 corresponds to the JSON schema field "content_sha256".
	ContentSha256 SHA256 `json:"content_sha256"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// InputHashes corresponds to the JSON schema field "input_hashes".
	InputHashes []SHA256 `json:"input_hashes"`

	// JobId corresponds to the JSON schema field "job_id".
	JobId Identifier `json:"job_id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ActionArtifactKind `json:"kind"`

	// NodeId corresponds to the JSON schema field "node_id".
	NodeId Identifier `json:"node_id"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion ActionArtifactSchemaVersion `json:"schema_version"`

	// WorkflowRef corresponds to the JSON schema field "workflow_ref".
	WorkflowRef WorkflowRef `json:"workflow_ref"`
}

type ActionArtifactApprovalState string

const ActionArtifactApprovalStateApproved ActionArtifactApprovalState = "approved"
const ActionArtifactApprovalStateNotRequired ActionArtifactApprovalState = "not_required"
const ActionArtifactApprovalStatePending ActionArtifactApprovalState = "pending"
const ActionArtifactApprovalStateRejected ActionArtifactApprovalState = "rejected"
const ActionArtifactApprovalStateStale ActionArtifactApprovalState = "stale"

type ActionArtifactKind string

const ActionArtifactKindActionArtifact ActionArtifactKind = "action_artifact"

type ActionArtifactSchemaVersion int

type AgentWorkflowContractCatalog struct {
	// ActionArtifact corresponds to the JSON schema field "action_artifact".
	ActionArtifact *ActionArtifact `json:"action_artifact,omitempty,omitzero"`

	// ApprovalBrief corresponds to the JSON schema field "approval_brief".
	ApprovalBrief *ApprovalBrief `json:"approval_brief,omitempty,omitzero"`

	// ApprovalPreview corresponds to the JSON schema field "approval_preview".
	ApprovalPreview *ApprovalPreview `json:"approval_preview,omitempty,omitzero"`

	// AttemptReservedEventPayload corresponds to the JSON schema field
	// "attempt_reserved_event_payload".
	AttemptReservedEventPayload *AttemptReservedEventPayload `json:"attempt_reserved_event_payload,omitempty,omitzero"`

	// AuthoringCatalog corresponds to the JSON schema field "authoring_catalog".
	AuthoringCatalog *AuthoringCatalog `json:"authoring_catalog,omitempty,omitzero"`

	// BudgetExhaustedEventPayload corresponds to the JSON schema field
	// "budget_exhausted_event_payload".
	BudgetExhaustedEventPayload *BudgetExhaustedEventPayload `json:"budget_exhausted_event_payload,omitempty,omitzero"`

	// CampaignAdmissionEventPayload corresponds to the JSON schema field
	// "campaign_admission_event_payload".
	CampaignAdmissionEventPayload *CampaignAdmissionEventPayload `json:"campaign_admission_event_payload,omitempty,omitzero"`

	// CampaignDefinition corresponds to the JSON schema field "campaign_definition".
	CampaignDefinition *CampaignDefinition `json:"campaign_definition,omitempty,omitzero"`

	// CampaignDrivePreview corresponds to the JSON schema field
	// "campaign_drive_preview".
	CampaignDrivePreview *CampaignDrivePreview `json:"campaign_drive_preview,omitempty,omitzero"`

	// CampaignDriveReceipt corresponds to the JSON schema field
	// "campaign_drive_receipt".
	CampaignDriveReceipt *CampaignDriveReceipt `json:"campaign_drive_receipt,omitempty,omitzero"`

	// CampaignExecutionState corresponds to the JSON schema field
	// "campaign_execution_state".
	CampaignExecutionState *CampaignExecutionState `json:"campaign_execution_state,omitempty,omitzero"`

	// CampaignTerminalEventPayload corresponds to the JSON schema field
	// "campaign_terminal_event_payload".
	CampaignTerminalEventPayload *CampaignTerminalEventPayload `json:"campaign_terminal_event_payload,omitempty,omitzero"`

	// CanvasSnapshot corresponds to the JSON schema field "canvas_snapshot".
	CanvasSnapshot *CanvasSnapshot `json:"canvas_snapshot,omitempty,omitzero"`

	// CapabilityManifest corresponds to the JSON schema field "capability_manifest".
	CapabilityManifest *CapabilityManifest `json:"capability_manifest,omitempty,omitzero"`

	// ContextBundle corresponds to the JSON schema field "context_bundle".
	ContextBundle *ContextBundle `json:"context_bundle,omitempty,omitzero"`

	// ContextPackEdition corresponds to the JSON schema field "context_pack_edition".
	ContextPackEdition *ContextPackEdition `json:"context_pack_edition,omitempty,omitzero"`

	// JobDefinition corresponds to the JSON schema field "job_definition".
	JobDefinition *JobDefinition `json:"job_definition,omitempty,omitzero"`

	// NodeCompletedEventPayload corresponds to the JSON schema field
	// "node_completed_event_payload".
	NodeCompletedEventPayload *NodeCompletedEventPayload `json:"node_completed_event_payload,omitempty,omitzero"`

	// Receipt corresponds to the JSON schema field "receipt".
	Receipt *Receipt `json:"receipt,omitempty,omitzero"`

	// ReplayBundle corresponds to the JSON schema field "replay_bundle".
	ReplayBundle *ReplayBundle `json:"replay_bundle,omitempty,omitzero"`

	// WorkflowAdmission corresponds to the JSON schema field "workflow_admission".
	WorkflowAdmission *WorkflowAdmission `json:"workflow_admission,omitempty,omitzero"`

	// WorkflowAdmissionPreview corresponds to the JSON schema field
	// "workflow_admission_preview".
	WorkflowAdmissionPreview *WorkflowAdmissionPreview `json:"workflow_admission_preview,omitempty,omitzero"`

	// WorkflowDefinition corresponds to the JSON schema field "workflow_definition".
	WorkflowDefinition *WorkflowDefinition `json:"workflow_definition,omitempty,omitzero"`

	// WorkflowLintReport corresponds to the JSON schema field "workflow_lint_report".
	WorkflowLintReport *WorkflowLintReport `json:"workflow_lint_report,omitempty,omitzero"`
}

type ApprovalBrief struct {
	// Action corresponds to the JSON schema field "action".
	Action ActionArtifact `json:"action"`

	// Evidence corresponds to the JSON schema field "evidence".
	Evidence []ArtifactRef `json:"evidence"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ApprovalBriefKind `json:"kind"`

	// Options corresponds to the JSON schema field "options".
	Options []ApprovalOption `json:"options"`

	// Recommendation corresponds to the JSON schema field "recommendation".
	Recommendation string `json:"recommendation"`

	// RecommendedOptionId corresponds to the JSON schema field
	// "recommended_option_id".
	RecommendedOptionId Identifier `json:"recommended_option_id"`

	// Risks corresponds to the JSON schema field "risks".
	Risks NonEmptyStrings `json:"risks"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion ApprovalBriefSchemaVersion `json:"schema_version"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`
}

type ApprovalBriefKind string

const ApprovalBriefKindApprovalBrief ApprovalBriefKind = "approval_brief"

type ApprovalBriefSchemaVersion int

type ApprovalOption struct {
	// Decision corresponds to the JSON schema field "decision".
	Decision ApprovalOptionDecision `json:"decision"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`

	// Tradeoffs corresponds to the JSON schema field "tradeoffs".
	Tradeoffs NonEmptyStrings `json:"tradeoffs"`
}

type ApprovalOptionDecision string

const ApprovalOptionDecisionApprove ApprovalOptionDecision = "approve"
const ApprovalOptionDecisionReject ApprovalOptionDecision = "reject"

type ApprovalPreview struct {
	// Actor corresponds to the JSON schema field "actor".
	Actor string `json:"actor"`

	// BaseRevision corresponds to the JSON schema field "base_revision".
	BaseRevision int `json:"base_revision"`

	// Brief corresponds to the JSON schema field "brief".
	Brief ApprovalBrief `json:"brief"`

	// BriefHash corresponds to the JSON schema field "brief_hash".
	BriefHash SHA256 `json:"brief_hash"`

	// CommitToken corresponds to the JSON schema field "commit_token".
	CommitToken SHA256 `json:"commit_token"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ApprovalPreviewKind `json:"kind"`

	// PreviewHash corresponds to the JSON schema field "preview_hash".
	PreviewHash SHA256 `json:"preview_hash"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion ApprovalPreviewSchemaVersion `json:"schema_version"`

	// SourceAggregateId corresponds to the JSON schema field "source_aggregate_id".
	SourceAggregateId string `json:"source_aggregate_id"`
}

type ApprovalPreviewKind string

const ApprovalPreviewKindApprovalPreview ApprovalPreviewKind = "approval_preview"

type ApprovalPreviewSchemaVersion int

type ArtifactRef struct {
	// ArtifactType corresponds to the JSON schema field "artifact_type".
	ArtifactType Identifier `json:"artifact_type"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ArtifactRefKind `json:"kind"`

	// MediaType corresponds to the JSON schema field "media_type".
	MediaType string `json:"media_type"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version"`

	// Sha256 corresponds to the JSON schema field "sha256".
	Sha256 SHA256 `json:"sha256"`
}

type ArtifactRefKind string

const ArtifactRefKindActionArtifact ArtifactRefKind = "action_artifact"
const ArtifactRefKindContextPack ArtifactRefKind = "context_pack"
const ArtifactRefKindReceipt ArtifactRefKind = "receipt"

type AttemptReservedEventPayload struct {
	// NodeId corresponds to the JSON schema field "node_id".
	NodeId Identifier `json:"node_id"`

	// StartedAt corresponds to the JSON schema field "started_at".
	StartedAt time.Time `json:"started_at"`

	// WorkflowRef corresponds to the JSON schema field "workflow_ref".
	WorkflowRef WorkflowRef `json:"workflow_ref"`
}

type AuthoringCatalog struct {
	// ApprovalPolicies corresponds to the JSON schema field "approval_policies".
	ApprovalPolicies Strings `json:"approval_policies"`

	// Blockers corresponds to the JSON schema field "blockers".
	Blockers Strings `json:"blockers"`

	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities []CatalogCapability `json:"capabilities"`

	// CatalogHash corresponds to the JSON schema field "catalog_hash".
	CatalogHash SHA256 `json:"catalog_hash"`

	// Executors corresponds to the JSON schema field "executors".
	Executors []CatalogExecutor `json:"executors"`

	// Kind corresponds to the JSON schema field "kind".
	Kind AuthoringCatalogKind `json:"kind"`

	// OutputSchemas corresponds to the JSON schema field "output_schemas".
	OutputSchemas []WorkflowRef `json:"output_schemas"`

	// Producers corresponds to the JSON schema field "producers".
	Producers []CatalogProducer `json:"producers"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion AuthoringCatalogSchemaVersion `json:"schema_version"`
}

type AuthoringCatalogKind string

const AuthoringCatalogKindAuthoringCatalog AuthoringCatalogKind = "authoring_catalog"

type AuthoringCatalogSchemaVersion int

type Budget struct {
	// MaxActions corresponds to the JSON schema field "max_actions".
	MaxActions int `json:"max_actions"`

	// MaxAttempts corresponds to the JSON schema field "max_attempts".
	MaxAttempts int `json:"max_attempts"`

	// MaxCandidates corresponds to the JSON schema field "max_candidates".
	MaxCandidates int `json:"max_candidates"`

	// MaxDurationSeconds corresponds to the JSON schema field "max_duration_seconds".
	MaxDurationSeconds *int `json:"max_duration_seconds,omitempty,omitzero"`
}

type BudgetExhaustedEventPayload struct {
	// BlockerCode corresponds to the JSON schema field "blocker_code".
	BlockerCode Identifier `json:"blocker_code"`

	// NodeId corresponds to the JSON schema field "node_id".
	NodeId Identifier `json:"node_id"`

	// ResultReplayHash corresponds to the JSON schema field "result_replay_hash".
	ResultReplayHash *SHA256 `json:"result_replay_hash,omitempty,omitzero"`

	// WorkflowRef corresponds to the JSON schema field "workflow_ref".
	WorkflowRef WorkflowRef `json:"workflow_ref"`
}

type CampaignAdmissionEventPayload struct {
	// State corresponds to the JSON schema field "state".
	State CampaignExecutionState `json:"state"`
}

type CampaignDefinition struct {
	// Archetype corresponds to the JSON schema field "archetype".
	Archetype Identifier `json:"archetype"`

	// Budget corresponds to the JSON schema field "budget".
	Budget Budget `json:"budget"`

	// DefinitionHash corresponds to the JSON schema field "definition_hash".
	DefinitionHash *SHA256 `json:"definition_hash,omitempty,omitzero"`

	// EvidenceFrontier corresponds to the JSON schema field "evidence_frontier".
	EvidenceFrontier EvidenceFrontier `json:"evidence_frontier"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id"`

	// Intent corresponds to the JSON schema field "intent".
	Intent IntentCard `json:"intent"`

	// JobId corresponds to the JSON schema field "job_id".
	JobId Identifier `json:"job_id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind CampaignDefinitionKind `json:"kind"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion CampaignDefinitionSchemaVersion `json:"schema_version"`

	// Scope corresponds to the JSON schema field "scope".
	Scope Scope `json:"scope"`

	// WorkflowPlan corresponds to the JSON schema field "workflow_plan".
	WorkflowPlan []WorkflowRef `json:"workflow_plan"`
}

type CampaignDefinitionKind string

const CampaignDefinitionKindCampaignDefinition CampaignDefinitionKind = "campaign_definition"

type CampaignDefinitionSchemaVersion int

type CampaignDrivePreview struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind CampaignDrivePreviewKind `json:"kind"`

	// NextAction corresponds to the JSON schema field "next_action".
	NextAction CampaignDrivePreviewNextAction `json:"next_action"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion CampaignDrivePreviewSchemaVersion `json:"schema_version"`

	// State corresponds to the JSON schema field "state".
	State CampaignExecutionState `json:"state"`
}

type CampaignDrivePreviewKind string

const CampaignDrivePreviewKindCampaignDrivePreview CampaignDrivePreviewKind = "campaign_drive_preview"

type CampaignDrivePreviewNextAction string

const CampaignDrivePreviewNextActionBlocked CampaignDrivePreviewNextAction = "blocked"
const CampaignDrivePreviewNextActionComplete CampaignDrivePreviewNextAction = "complete"
const CampaignDrivePreviewNextActionRunNode CampaignDrivePreviewNextAction = "run_node"
const CampaignDrivePreviewNextActionWait CampaignDrivePreviewNextAction = "wait"

type CampaignDrivePreviewSchemaVersion int

type CampaignDriveReceipt struct {
	// CampaignReplay corresponds to the JSON schema field "campaign_replay".
	CampaignReplay *ReplayBundle `json:"campaign_replay,omitempty,omitzero"`

	// Kind corresponds to the JSON schema field "kind".
	Kind CampaignDriveReceiptKind `json:"kind"`

	// NodeReplay corresponds to the JSON schema field "node_replay".
	NodeReplay *ReplayBundle `json:"node_replay,omitempty,omitzero"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion CampaignDriveReceiptSchemaVersion `json:"schema_version"`

	// State corresponds to the JSON schema field "state".
	State CampaignExecutionState `json:"state"`

	// Transitions corresponds to the JSON schema field "transitions".
	Transitions int `json:"transitions"`
}

type CampaignDriveReceiptKind string

const CampaignDriveReceiptKindCampaignDriveReceipt CampaignDriveReceiptKind = "campaign_drive_receipt"

type CampaignDriveReceiptSchemaVersion int

type CampaignExecutionState struct {
	// AggregateId corresponds to the JSON schema field "aggregate_id".
	AggregateId string `json:"aggregate_id"`

	// BlockerCode corresponds to the JSON schema field "blocker_code".
	BlockerCode *Identifier `json:"blocker_code,omitempty,omitzero"`

	// CampaignHash corresponds to the JSON schema field "campaign_hash".
	CampaignHash SHA256 `json:"campaign_hash"`

	// CampaignId corresponds to the JSON schema field "campaign_id".
	CampaignId Identifier `json:"campaign_id"`

	// JobHash corresponds to the JSON schema field "job_hash".
	JobHash SHA256 `json:"job_hash"`

	// JobId corresponds to the JSON schema field "job_id".
	JobId Identifier `json:"job_id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind CampaignExecutionStateKind `json:"kind"`

	// NextNodeId corresponds to the JSON schema field "next_node_id".
	NextNodeId *Identifier `json:"next_node_id,omitempty,omitzero"`

	// NextWorkflowRef corresponds to the JSON schema field "next_workflow_ref".
	NextWorkflowRef *WorkflowRef `json:"next_workflow_ref,omitempty,omitzero"`

	// Nodes corresponds to the JSON schema field "nodes".
	Nodes []CampaignNodeExecution `json:"nodes"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion CampaignExecutionStateSchemaVersion `json:"schema_version"`

	// StartedAt corresponds to the JSON schema field "started_at".
	StartedAt time.Time `json:"started_at"`

	// Status corresponds to the JSON schema field "status".
	Status CampaignExecutionStateStatus `json:"status"`

	// UpdatedAt corresponds to the JSON schema field "updated_at".
	UpdatedAt time.Time `json:"updated_at"`

	// Usage corresponds to the JSON schema field "usage".
	Usage CampaignExecutionUsage `json:"usage"`

	// WorkflowHashes corresponds to the JSON schema field "workflow_hashes".
	WorkflowHashes CampaignExecutionStateWorkflowHashes `json:"workflow_hashes"`
}

type CampaignExecutionStateKind string

const CampaignExecutionStateKindCampaignExecutionState CampaignExecutionStateKind = "campaign_execution_state"

type CampaignExecutionStateSchemaVersion int

type CampaignExecutionStateStatus string

const CampaignExecutionStateStatusAdmitted CampaignExecutionStateStatus = "admitted"
const CampaignExecutionStateStatusBlocked CampaignExecutionStateStatus = "blocked"
const CampaignExecutionStateStatusCompleted CampaignExecutionStateStatus = "completed"
const CampaignExecutionStateStatusRunning CampaignExecutionStateStatus = "running"
const CampaignExecutionStateStatusTerminal CampaignExecutionStateStatus = "terminal"

type CampaignExecutionStateWorkflowHashes map[string]SHA256

type CampaignExecutionUsage struct {
	// Actions corresponds to the JSON schema field "actions".
	Actions int `json:"actions"`

	// Attempts corresponds to the JSON schema field "attempts".
	Attempts int `json:"attempts"`

	// Candidates corresponds to the JSON schema field "candidates".
	Candidates int `json:"candidates"`

	// DurationSeconds corresponds to the JSON schema field "duration_seconds".
	DurationSeconds int `json:"duration_seconds"`
}

type CampaignNodeExecution struct {
	// BlockerCode corresponds to the JSON schema field "blocker_code".
	BlockerCode *Identifier `json:"blocker_code,omitempty,omitzero"`

	// CompletedAt corresponds to the JSON schema field "completed_at".
	CompletedAt *time.Time `json:"completed_at,omitempty,omitzero"`

	// NodeId corresponds to the JSON schema field "node_id".
	NodeId Identifier `json:"node_id"`

	// ResultReplayHash corresponds to the JSON schema field "result_replay_hash".
	ResultReplayHash *SHA256 `json:"result_replay_hash,omitempty,omitzero"`

	// StartedAt corresponds to the JSON schema field "started_at".
	StartedAt *time.Time `json:"started_at,omitempty,omitzero"`

	// Status corresponds to the JSON schema field "status".
	Status CampaignNodeExecutionStatus `json:"status"`

	// Usage corresponds to the JSON schema field "usage".
	Usage CampaignExecutionUsage `json:"usage"`

	// WorkflowRef corresponds to the JSON schema field "workflow_ref".
	WorkflowRef WorkflowRef `json:"workflow_ref"`
}

type CampaignNodeExecutionStatus string

const CampaignNodeExecutionStatusBlocked CampaignNodeExecutionStatus = "blocked"
const CampaignNodeExecutionStatusBudgetExhausted CampaignNodeExecutionStatus = "budget_exhausted"
const CampaignNodeExecutionStatusCompleted CampaignNodeExecutionStatus = "completed"
const CampaignNodeExecutionStatusCompletedNoAction CampaignNodeExecutionStatus = "completed_no_action"
const CampaignNodeExecutionStatusPending CampaignNodeExecutionStatus = "pending"
const CampaignNodeExecutionStatusRunning CampaignNodeExecutionStatus = "running"

type CampaignTerminalEventPayload struct {
	// State corresponds to the JSON schema field "state".
	State interface{} `json:"state"`
}

type CanvasContextPort struct {
	// AllowPartial corresponds to the JSON schema field "allow_partial".
	AllowPartial bool `json:"allow_partial"`

	// Consumers corresponds to the JSON schema field "consumers".
	Consumers Strings `json:"consumers"`

	// Edition corresponds to the JSON schema field "edition".
	Edition *ContextPackEdition `json:"edition,omitempty,omitzero"`

	// EvidenceFrontier corresponds to the JSON schema field "evidence_frontier".
	EvidenceFrontier EvidenceFrontier `json:"evidence_frontier"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id"`

	// NodeId corresponds to the JSON schema field "node_id".
	NodeId Identifier `json:"node_id"`

	// PackType corresponds to the JSON schema field "pack_type".
	PackType Identifier `json:"pack_type"`

	// Producer corresponds to the JSON schema field "producer".
	Producer Identifier `json:"producer"`

	// Required corresponds to the JSON schema field "required".
	Required bool `json:"required"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version"`

	// Selector corresponds to the JSON schema field "selector".
	Selector Identifier `json:"selector"`

	// Status corresponds to the JSON schema field "status".
	Status CanvasContextStatus `json:"status"`
}

type CanvasContextStatus string

const CanvasContextStatusConfigured CanvasContextStatus = "configured"
const CanvasContextStatusDegraded CanvasContextStatus = "degraded"
const CanvasContextStatusInvalid CanvasContextStatus = "invalid"
const CanvasContextStatusMissing CanvasContextStatus = "missing"
const CanvasContextStatusPartial CanvasContextStatus = "partial"
const CanvasContextStatusResolved CanvasContextStatus = "resolved"
const CanvasContextStatusStale CanvasContextStatus = "stale"

type CanvasDefinitionGraph struct {
	// Campaign corresponds to the JSON schema field "campaign".
	Campaign CampaignDefinition `json:"campaign"`

	// CampaignState corresponds to the JSON schema field "campaign_state".
	CampaignState CanvasEntityStatus `json:"campaign_state"`

	// Job corresponds to the JSON schema field "job".
	Job JobDefinition `json:"job"`

	// WorkflowStates corresponds to the JSON schema field "workflow_states".
	WorkflowStates CanvasDefinitionGraphWorkflowStates `json:"workflow_states,omitempty,omitzero"`

	// Workflows corresponds to the JSON schema field "workflows".
	Workflows []WorkflowDefinition `json:"workflows"`
}

type CanvasDefinitionGraphWorkflowStates map[string]CanvasEntityStatus

type CanvasEntityStatus string

const CanvasEntityStatusAdmitted CanvasEntityStatus = "admitted"
const CanvasEntityStatusAwaitingHuman CanvasEntityStatus = "awaiting_human"
const CanvasEntityStatusBlocked CanvasEntityStatus = "blocked"
const CanvasEntityStatusCompleted CanvasEntityStatus = "completed"
const CanvasEntityStatusConfigured CanvasEntityStatus = "configured"
const CanvasEntityStatusEligible CanvasEntityStatus = "eligible"
const CanvasEntityStatusRunning CanvasEntityStatus = "running"
const CanvasEntityStatusTerminal CanvasEntityStatus = "terminal"

type CanvasExecution struct {
	// AggregateId corresponds to the JSON schema field "aggregate_id".
	AggregateId string `json:"aggregate_id"`

	// ApprovalState corresponds to the JSON schema field "approval_state".
	ApprovalState CanvasExecutionApprovalState `json:"approval_state"`

	// BlockerCode corresponds to the JSON schema field "blocker_code".
	BlockerCode *Identifier `json:"blocker_code,omitempty,omitzero"`

	// BlockerMessage corresponds to the JSON schema field "blocker_message".
	BlockerMessage *string `json:"blocker_message,omitempty,omitzero"`

	// Bundle corresponds to the JSON schema field "bundle".
	Bundle ContextBundle `json:"bundle"`

	// ContextPorts corresponds to the JSON schema field "context_ports".
	ContextPorts []CanvasContextPort `json:"context_ports"`

	// Deadline corresponds to the JSON schema field "deadline".
	Deadline time.Time `json:"deadline"`

	// NodeId corresponds to the JSON schema field "node_id".
	NodeId Identifier `json:"node_id"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs []ActionArtifact `json:"outputs"`

	// Receipts corresponds to the JSON schema field "receipts".
	Receipts []CanvasReceiptLink `json:"receipts"`

	// Status corresponds to the JSON schema field "status".
	Status CanvasEntityStatus `json:"status"`
}

type CanvasExecutionApprovalState string

const CanvasExecutionApprovalStateApproved CanvasExecutionApprovalState = "approved"
const CanvasExecutionApprovalStateNotRequired CanvasExecutionApprovalState = "not_required"
const CanvasExecutionApprovalStatePending CanvasExecutionApprovalState = "pending"
const CanvasExecutionApprovalStateRejected CanvasExecutionApprovalState = "rejected"
const CanvasExecutionApprovalStateStale CanvasExecutionApprovalState = "stale"

type CanvasNextSafeAction struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind CanvasNextSafeActionKind `json:"kind"`

	// NodeId corresponds to the JSON schema field "node_id".
	NodeId *Identifier `json:"node_id,omitempty,omitzero"`

	// Reason corresponds to the JSON schema field "reason".
	Reason string `json:"reason"`

	// WorkflowRef corresponds to the JSON schema field "workflow_ref".
	WorkflowRef *WorkflowRef `json:"workflow_ref,omitempty,omitzero"`
}

type CanvasNextSafeActionKind string

const CanvasNextSafeActionKindNone CanvasNextSafeActionKind = "none"
const CanvasNextSafeActionKindRequestApproval CanvasNextSafeActionKind = "request_approval"
const CanvasNextSafeActionKindRequestContext CanvasNextSafeActionKind = "request_context"
const CanvasNextSafeActionKindRetry CanvasNextSafeActionKind = "retry"
const CanvasNextSafeActionKindStartNode CanvasNextSafeActionKind = "start_node"
const CanvasNextSafeActionKindTerminal CanvasNextSafeActionKind = "terminal"

type CanvasReceiptLink struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// OccurredAt corresponds to the JSON schema field "occurred_at".
	OccurredAt time.Time `json:"occurred_at"`

	// ReceiptHash corresponds to the JSON schema field "receipt_hash".
	ReceiptHash SHA256 `json:"receipt_hash"`

	// ReceiptType corresponds to the JSON schema field "receipt_type".
	ReceiptType CanvasReceiptLinkReceiptType `json:"receipt_type"`
}

type CanvasReceiptLinkReceiptType string

const CanvasReceiptLinkReceiptTypeAdmission CanvasReceiptLinkReceiptType = "admission"
const CanvasReceiptLinkReceiptTypeApproval CanvasReceiptLinkReceiptType = "approval"
const CanvasReceiptLinkReceiptTypeAttemptReserved CanvasReceiptLinkReceiptType = "attempt_reserved"
const CanvasReceiptLinkReceiptTypeBudgetExhausted CanvasReceiptLinkReceiptType = "budget_exhausted"
const CanvasReceiptLinkReceiptTypeCampaignAdmission CanvasReceiptLinkReceiptType = "campaign_admission"
const CanvasReceiptLinkReceiptTypeCompile CanvasReceiptLinkReceiptType = "compile"
const CanvasReceiptLinkReceiptTypeInvocation CanvasReceiptLinkReceiptType = "invocation"
const CanvasReceiptLinkReceiptTypeNodeCompleted CanvasReceiptLinkReceiptType = "node_completed"
const CanvasReceiptLinkReceiptTypePackEdition CanvasReceiptLinkReceiptType = "pack_edition"
const CanvasReceiptLinkReceiptTypeProviderExecution CanvasReceiptLinkReceiptType = "provider_execution"
const CanvasReceiptLinkReceiptTypeResult CanvasReceiptLinkReceiptType = "result"
const CanvasReceiptLinkReceiptTypeTerminal CanvasReceiptLinkReceiptType = "terminal"

type CanvasSnapshot struct {
	// AdmissionReplays corresponds to the JSON schema field "admission_replays".
	AdmissionReplays []ReplayBundle `json:"admission_replays,omitempty,omitzero"`

	// ApprovalReplays corresponds to the JSON schema field "approval_replays".
	ApprovalReplays []ReplayBundle `json:"approval_replays,omitempty,omitzero"`

	// Definition corresponds to the JSON schema field "definition".
	Definition CanvasDefinitionGraph `json:"definition"`

	// Executions corresponds to the JSON schema field "executions".
	Executions []CanvasExecution `json:"executions"`

	// GeneratedAt corresponds to the JSON schema field "generated_at".
	GeneratedAt time.Time `json:"generated_at"`

	// Kind corresponds to the JSON schema field "kind".
	Kind CanvasSnapshotKind `json:"kind"`

	// NextSafeAction corresponds to the JSON schema field "next_safe_action".
	NextSafeAction CanvasNextSafeAction `json:"next_safe_action"`

	// Replays corresponds to the JSON schema field "replays".
	Replays []ReplayBundle `json:"replays"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion CanvasSnapshotSchemaVersion `json:"schema_version"`
}

type CanvasSnapshotKind string

const CanvasSnapshotKindCanvasSnapshot CanvasSnapshotKind = "canvas_snapshot"

type CanvasSnapshotSchemaVersion int

type CapabilityManifest struct {
	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities []CapabilityManifestCapabilitiesElem `json:"capabilities"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind CapabilityManifestKind `json:"kind"`

	// ManifestHash corresponds to the JSON schema field "manifest_hash".
	ManifestHash SHA256 `json:"manifest_hash"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion CapabilityManifestSchemaVersion `json:"schema_version"`
}

type CapabilityManifestCapabilitiesElem struct {
	// Authority corresponds to the JSON schema field "authority".
	Authority CapabilityManifestCapabilitiesElemAuthority `json:"authority"`

	// Name corresponds to the JSON schema field "name".
	Name Identifier `json:"name"`
}

type CapabilityManifestCapabilitiesElemAuthority string

const CapabilityManifestCapabilitiesElemAuthorityCanonicalMutation CapabilityManifestCapabilitiesElemAuthority = "canonical_mutation"
const CapabilityManifestCapabilitiesElemAuthorityExternalMutation CapabilityManifestCapabilitiesElemAuthority = "external_mutation"
const CapabilityManifestCapabilitiesElemAuthorityLocalMutation CapabilityManifestCapabilitiesElemAuthority = "local_mutation"
const CapabilityManifestCapabilitiesElemAuthorityRead CapabilityManifestCapabilitiesElemAuthority = "read"
const CapabilityManifestCapabilitiesElemAuthoritySystemRecovery CapabilityManifestCapabilitiesElemAuthority = "system_recovery"

type CapabilityManifestKind string

const CapabilityManifestKindCapabilityManifest CapabilityManifestKind = "capability_manifest"

type CapabilityManifestSchemaVersion int

type CatalogCapability struct {
	// Authority corresponds to the JSON schema field "authority".
	Authority CatalogCapabilityAuthority `json:"authority"`

	// Name corresponds to the JSON schema field "name".
	Name Identifier `json:"name"`
}

type CatalogCapabilityAuthority string

const CatalogCapabilityAuthorityCanonicalMutation CatalogCapabilityAuthority = "canonical_mutation"
const CatalogCapabilityAuthorityExternalMutation CatalogCapabilityAuthority = "external_mutation"
const CatalogCapabilityAuthorityLocalMutation CatalogCapabilityAuthority = "local_mutation"
const CatalogCapabilityAuthorityRead CatalogCapabilityAuthority = "read"
const CatalogCapabilityAuthoritySystemRecovery CatalogCapabilityAuthority = "system_recovery"

type CatalogExecutor struct {
	// NodeKind corresponds to the JSON schema field "node_kind".
	NodeKind CatalogExecutorNodeKind `json:"node_kind"`

	// Ref corresponds to the JSON schema field "ref".
	Ref WorkflowRef `json:"ref"`
}

type CatalogExecutorNodeKind string

const CatalogExecutorNodeKindAgent CatalogExecutorNodeKind = "agent"
const CatalogExecutorNodeKindApproval CatalogExecutorNodeKind = "approval"
const CatalogExecutorNodeKindDeterministic CatalogExecutorNodeKind = "deterministic"
const CatalogExecutorNodeKindTerminal CatalogExecutorNodeKind = "terminal"
const CatalogExecutorNodeKindWait CatalogExecutorNodeKind = "wait"

type CatalogProducer struct {
	// PackType corresponds to the JSON schema field "pack_type".
	PackType Identifier `json:"pack_type"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version"`

	// Selector corresponds to the JSON schema field "selector".
	Selector Identifier `json:"selector"`
}

type ContextBundle struct {
	// BundleHash corresponds to the JSON schema field "bundle_hash".
	BundleHash SHA256 `json:"bundle_hash"`

	// CampaignId corresponds to the JSON schema field "campaign_id".
	CampaignId Identifier `json:"campaign_id"`

	// Degraded corresponds to the JSON schema field "degraded".
	Degraded bool `json:"degraded"`

	// Entries corresponds to the JSON schema field "entries".
	Entries []ContextPackRef `json:"entries"`

	// EvidenceCutoff corresponds to the JSON schema field "evidence_cutoff".
	EvidenceCutoff time.Time `json:"evidence_cutoff"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// JobId corresponds to the JSON schema field "job_id".
	JobId Identifier `json:"job_id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ContextBundleKind `json:"kind"`

	// MissingOptional corresponds to the JSON schema field "missing_optional".
	MissingOptional Strings `json:"missing_optional,omitempty,omitzero"`

	// NodeId corresponds to the JSON schema field "node_id".
	NodeId Identifier `json:"node_id"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion ContextBundleSchemaVersion `json:"schema_version"`

	// WorkflowRef corresponds to the JSON schema field "workflow_ref".
	WorkflowRef WorkflowRef `json:"workflow_ref"`
}

type ContextBundleKind string

const ContextBundleKindContextBundle ContextBundleKind = "context_bundle"

type ContextBundleSchemaVersion int

type ContextPackEdition struct {
	// Authority corresponds to the JSON schema field "authority".
	Authority ContextPackEditionAuthority `json:"authority"`

	// CapturedAt corresponds to the JSON schema field "captured_at".
	CapturedAt time.Time `json:"captured_at"`

	// Content corresponds to the JSON schema field "content".
	Content interface{} `json:"content"`

	// ContentSha256 corresponds to the JSON schema field "content_sha256".
	ContentSha256 SHA256 `json:"content_sha256"`

	// Coverage corresponds to the JSON schema field "coverage".
	Coverage ContextPackEditionCoverage `json:"coverage"`

	// ExpiresAt corresponds to the JSON schema field "expires_at".
	ExpiresAt time.Time `json:"expires_at"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ContextPackEditionKind `json:"kind"`

	// PackSchemaVersion corresponds to the JSON schema field "pack_schema_version".
	PackSchemaVersion int `json:"pack_schema_version"`

	// PackType corresponds to the JSON schema field "pack_type".
	PackType Identifier `json:"pack_type"`

	// Provenance corresponds to the JSON schema field "provenance".
	Provenance []ArtifactRef `json:"provenance"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion ContextPackEditionSchemaVersion `json:"schema_version"`

	// Scope corresponds to the JSON schema field "scope".
	Scope Scope `json:"scope"`

	// SupersedesEditionId corresponds to the JSON schema field
	// "supersedes_edition_id".
	SupersedesEditionId *string `json:"supersedes_edition_id,omitempty,omitzero"`
}

type ContextPackEditionAuthority string

const ContextPackEditionAuthorityCanonical ContextPackEditionAuthority = "canonical"
const ContextPackEditionAuthorityDerived ContextPackEditionAuthority = "derived"
const ContextPackEditionAuthorityExternalObservation ContextPackEditionAuthority = "external_observation"

type ContextPackEditionCoverage string

const ContextPackEditionCoverageComplete ContextPackEditionCoverage = "complete"
const ContextPackEditionCoveragePartial ContextPackEditionCoverage = "partial"

type ContextPackEditionKind string

const ContextPackEditionKindContextPackEdition ContextPackEditionKind = "context_pack_edition"

type ContextPackEditionSchemaVersion int

type ContextPackRef struct {
	// ArtifactType corresponds to the JSON schema field "artifact_type".
	ArtifactType Identifier `json:"artifact_type"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ContextPackRefKind `json:"kind"`

	// MediaType corresponds to the JSON schema field "media_type".
	MediaType string `json:"media_type"`

	// RequirementId corresponds to the JSON schema field "requirement_id".
	RequirementId *Identifier `json:"requirement_id,omitempty,omitzero"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version"`

	// Sha256 corresponds to the JSON schema field "sha256".
	Sha256 SHA256 `json:"sha256"`
}

type ContextPackRefKind string

const ContextPackRefKindContextPack ContextPackRefKind = "context_pack"

type ContextRequirement struct {
	// AllowPartial corresponds to the JSON schema field "allow_partial".
	AllowPartial bool `json:"allow_partial"`

	// EditionId corresponds to the JSON schema field "edition_id".
	EditionId *string `json:"edition_id,omitempty,omitzero"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id"`

	// MaxAgeSeconds corresponds to the JSON schema field "max_age_seconds".
	MaxAgeSeconds *int `json:"max_age_seconds,omitempty,omitzero"`

	// PackType corresponds to the JSON schema field "pack_type".
	PackType Identifier `json:"pack_type"`

	// Required corresponds to the JSON schema field "required".
	Required bool `json:"required"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version"`

	// Selector corresponds to the JSON schema field "selector".
	Selector Identifier `json:"selector"`

	// SubjectKey corresponds to the JSON schema field "subject_key".
	SubjectKey *string `json:"subject_key,omitempty,omitzero"`
}

type EvidenceFrontier struct {
	// Cutoff corresponds to the JSON schema field "cutoff".
	Cutoff time.Time `json:"cutoff"`

	// SourceHashes corresponds to the JSON schema field "source_hashes".
	SourceHashes []SHA256 `json:"source_hashes"`
}

type ExpandedNodeContract struct {
	// ContextAuthorities corresponds to the JSON schema field "context_authorities".
	ContextAuthorities []ExpandedNodeContractContextAuthoritiesElem `json:"context_authorities"`

	// Definition corresponds to the JSON schema field "definition".
	Definition NodeDefinition `json:"definition"`
}

type ExpandedNodeContractContextAuthoritiesElem string

const ExpandedNodeContractContextAuthoritiesElemCanonical ExpandedNodeContractContextAuthoritiesElem = "canonical"
const ExpandedNodeContractContextAuthoritiesElemDerived ExpandedNodeContractContextAuthoritiesElem = "derived"
const ExpandedNodeContractContextAuthoritiesElemExternalObservation ExpandedNodeContractContextAuthoritiesElem = "external_observation"

type Identifier string

type IntentCard struct {
	// Completion corresponds to the JSON schema field "completion".
	Completion NonEmptyStrings `json:"completion"`

	// Consumers corresponds to the JSON schema field "consumers".
	Consumers Strings `json:"consumers,omitempty,omitzero"`

	// DescriptorHash corresponds to the JSON schema field "descriptor_hash".
	DescriptorHash *SHA256 `json:"descriptor_hash,omitempty,omitzero"`

	// Kind corresponds to the JSON schema field "kind".
	Kind IntentCardKind `json:"kind"`

	// NoActionWhen corresponds to the JSON schema field "no_action_when".
	NoActionWhen NonEmptyStrings `json:"no_action_when"`

	// NonGoals corresponds to the JSON schema field "non_goals".
	NonGoals NonEmptyStrings `json:"non_goals"`

	// Objective corresponds to the JSON schema field "objective".
	Objective string `json:"objective"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion IntentCardSchemaVersion `json:"schema_version"`

	// SuccessSignals corresponds to the JSON schema field "success_signals".
	SuccessSignals NonEmptyStrings `json:"success_signals"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary"`

	// Tags corresponds to the JSON schema field "tags".
	Tags Strings `json:"tags,omitempty,omitzero"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`
}

type IntentCardKind string

const IntentCardKindCampaign IntentCardKind = "campaign"
const IntentCardKindJob IntentCardKind = "job"
const IntentCardKindWorkflow IntentCardKind = "workflow"

type IntentCardSchemaVersion int

type JobDefinition struct {
	// Budget corresponds to the JSON schema field "budget".
	Budget Budget `json:"budget"`

	// CampaignArchetypes corresponds to the JSON schema field "campaign_archetypes".
	CampaignArchetypes NonEmptyStrings `json:"campaign_archetypes"`

	// DefinitionHash corresponds to the JSON schema field "definition_hash".
	DefinitionHash *SHA256 `json:"definition_hash,omitempty,omitzero"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id"`

	// Intent corresponds to the JSON schema field "intent".
	Intent IntentCard `json:"intent"`

	// Kind corresponds to the JSON schema field "kind".
	Kind JobDefinitionKind `json:"kind"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion JobDefinitionSchemaVersion `json:"schema_version"`

	// Scope corresponds to the JSON schema field "scope".
	Scope Scope `json:"scope"`
}

type JobDefinitionKind string

const JobDefinitionKindJobDefinition JobDefinitionKind = "job_definition"

type JobDefinitionSchemaVersion int

type NodeCompletedEventPayload struct {
	// CompletedAt corresponds to the JSON schema field "completed_at".
	CompletedAt time.Time `json:"completed_at"`

	// NodeId corresponds to the JSON schema field "node_id".
	NodeId Identifier `json:"node_id"`

	// ResultReplayHash corresponds to the JSON schema field "result_replay_hash".
	ResultReplayHash SHA256 `json:"result_replay_hash"`

	// Status corresponds to the JSON schema field "status".
	Status NodeCompletedEventPayloadStatus `json:"status"`

	// Usage corresponds to the JSON schema field "usage".
	Usage CampaignExecutionUsage `json:"usage"`

	// WorkflowRef corresponds to the JSON schema field "workflow_ref".
	WorkflowRef WorkflowRef `json:"workflow_ref"`
}

type NodeCompletedEventPayloadStatus string

const NodeCompletedEventPayloadStatusCompleted NodeCompletedEventPayloadStatus = "completed"
const NodeCompletedEventPayloadStatusCompletedNoAction NodeCompletedEventPayloadStatus = "completed_no_action"

type NodeDefinition struct {
	// ApprovalPolicy corresponds to the JSON schema field "approval_policy".
	ApprovalPolicy *Identifier `json:"approval_policy,omitempty,omitzero"`

	// BlockerCodes corresponds to the JSON schema field "blocker_codes".
	BlockerCodes Strings `json:"blocker_codes,omitempty,omitzero"`

	// Budget corresponds to the JSON schema field "budget".
	Budget Budget `json:"budget"`

	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities Strings `json:"capabilities"`

	// Context corresponds to the JSON schema field "context".
	Context []ContextRequirement `json:"context"`

	// DeadlineSeconds corresponds to the JSON schema field "deadline_seconds".
	DeadlineSeconds *int `json:"deadline_seconds,omitempty,omitzero"`

	// DependsOn corresponds to the JSON schema field "depends_on".
	DependsOn Strings `json:"depends_on"`

	// Executor corresponds to the JSON schema field "executor".
	Executor string `json:"executor"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id"`

	// InputSlots corresponds to the JSON schema field "input_slots".
	InputSlots []Slot `json:"input_slots"`

	// Kind corresponds to the JSON schema field "kind".
	Kind NodeDefinitionKind `json:"kind"`

	// OutputSlots corresponds to the JSON schema field "output_slots".
	OutputSlots []Slot `json:"output_slots"`
}

type NodeDefinitionKind string

const NodeDefinitionKindAgent NodeDefinitionKind = "agent"
const NodeDefinitionKindApproval NodeDefinitionKind = "approval"
const NodeDefinitionKindDeterministic NodeDefinitionKind = "deterministic"
const NodeDefinitionKindTerminal NodeDefinitionKind = "terminal"
const NodeDefinitionKindWait NodeDefinitionKind = "wait"

type NonEmptyStrings []string

type Receipt struct {
	// Actor corresponds to the JSON schema field "actor".
	Actor *string `json:"actor,omitempty,omitzero"`

	// AggregateId corresponds to the JSON schema field "aggregate_id".
	AggregateId string `json:"aggregate_id"`

	// AggregateVersion corresponds to the JSON schema field "aggregate_version".
	AggregateVersion int `json:"aggregate_version"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id"`

	// InputHashes corresponds to the JSON schema field "input_hashes".
	InputHashes []SHA256 `json:"input_hashes"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ReceiptKind `json:"kind"`

	// OccurredAt corresponds to the JSON schema field "occurred_at".
	OccurredAt time.Time `json:"occurred_at"`

	// OutputHashes corresponds to the JSON schema field "output_hashes".
	OutputHashes []SHA256 `json:"output_hashes"`

	// Payload corresponds to the JSON schema field "payload".
	Payload ReceiptPayload `json:"payload,omitempty,omitzero"`

	// PreviousReceiptHash corresponds to the JSON schema field
	// "previous_receipt_hash".
	PreviousReceiptHash interface{} `json:"previous_receipt_hash"`

	// ReceiptHash corresponds to the JSON schema field "receipt_hash".
	ReceiptHash SHA256 `json:"receipt_hash"`

	// ReceiptType corresponds to the JSON schema field "receipt_type".
	ReceiptType ReceiptReceiptType `json:"receipt_type"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion ReceiptSchemaVersion `json:"schema_version"`
}

type ReceiptKind string

const ReceiptKindReceipt ReceiptKind = "receipt"

type ReceiptPayload map[string]interface{}

type ReceiptReceiptType string

const ReceiptReceiptTypeAdmission ReceiptReceiptType = "admission"
const ReceiptReceiptTypeApproval ReceiptReceiptType = "approval"
const ReceiptReceiptTypeAttemptReserved ReceiptReceiptType = "attempt_reserved"
const ReceiptReceiptTypeBudgetExhausted ReceiptReceiptType = "budget_exhausted"
const ReceiptReceiptTypeCampaignAdmission ReceiptReceiptType = "campaign_admission"
const ReceiptReceiptTypeCompile ReceiptReceiptType = "compile"
const ReceiptReceiptTypeInvocation ReceiptReceiptType = "invocation"
const ReceiptReceiptTypeNodeCompleted ReceiptReceiptType = "node_completed"
const ReceiptReceiptTypePackEdition ReceiptReceiptType = "pack_edition"
const ReceiptReceiptTypeProviderExecution ReceiptReceiptType = "provider_execution"
const ReceiptReceiptTypeResult ReceiptReceiptType = "result"
const ReceiptReceiptTypeTerminal ReceiptReceiptType = "terminal"

type ReceiptSchemaVersion int

type ReplayBundle struct {
	// AggregateId corresponds to the JSON schema field "aggregate_id".
	AggregateId string `json:"aggregate_id"`

	// BundleHash corresponds to the JSON schema field "bundle_hash".
	BundleHash SHA256 `json:"bundle_hash"`

	// CutoffReceiptHash corresponds to the JSON schema field "cutoff_receipt_hash".
	CutoffReceiptHash SHA256 `json:"cutoff_receipt_hash"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ReplayBundleKind `json:"kind"`

	// Receipts corresponds to the JSON schema field "receipts".
	Receipts []Receipt `json:"receipts"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion ReplayBundleSchemaVersion `json:"schema_version"`
}

type ReplayBundleKind string

const ReplayBundleKindReplayBundle ReplayBundleKind = "replay_bundle"

type ReplayBundleSchemaVersion int

type SHA256 string

type Scope struct {
	// Labels corresponds to the JSON schema field "labels".
	Labels ScopeLabels `json:"labels,omitempty,omitzero"`

	// SubjectIds corresponds to the JSON schema field "subject_ids".
	SubjectIds NonEmptyStrings `json:"subject_ids"`

	// SubjectType corresponds to the JSON schema field "subject_type".
	SubjectType Identifier `json:"subject_type"`
}

type ScopeLabels map[string]string

type Slot struct {
	// ArtifactKind corresponds to the JSON schema field "artifact_kind".
	ArtifactKind *SlotArtifactKind `json:"artifact_kind,omitempty,omitzero"`

	// ArtifactType corresponds to the JSON schema field "artifact_type".
	ArtifactType Identifier `json:"artifact_type"`

	// Consumers corresponds to the JSON schema field "consumers".
	Consumers Strings `json:"consumers,omitempty,omitzero"`

	// ContentSchema corresponds to the JSON schema field "content_schema".
	ContentSchema *WorkflowRef `json:"content_schema,omitempty,omitzero"`

	// CountsAsCandidates corresponds to the JSON schema field "counts_as_candidates".
	CountsAsCandidates bool `json:"counts_as_candidates,omitempty,omitzero"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id"`

	// MaxItems corresponds to the JSON schema field "max_items".
	MaxItems int `json:"max_items"`

	// MinItems corresponds to the JSON schema field "min_items".
	MinItems int `json:"min_items"`
}

type SlotArtifactKind string

const SlotArtifactKindActionArtifact SlotArtifactKind = "action_artifact"
const SlotArtifactKindContextPack SlotArtifactKind = "context_pack"

type Strings []string

type WorkflowAdmission struct {
	// Campaign corresponds to the JSON schema field "campaign".
	Campaign CampaignDefinition `json:"campaign"`

	// CampaignHash corresponds to the JSON schema field "campaign_hash".
	CampaignHash SHA256 `json:"campaign_hash"`

	// CompileHash corresponds to the JSON schema field "compile_hash".
	CompileHash SHA256 `json:"compile_hash"`

	// DefinitionHash corresponds to the JSON schema field "definition_hash".
	DefinitionHash SHA256 `json:"definition_hash"`

	// Job corresponds to the JSON schema field "job".
	Job JobDefinition `json:"job"`

	// JobHash corresponds to the JSON schema field "job_hash".
	JobHash SHA256 `json:"job_hash"`

	// Kind corresponds to the JSON schema field "kind".
	Kind WorkflowAdmissionKind `json:"kind"`

	// PreviewHash corresponds to the JSON schema field "preview_hash".
	PreviewHash SHA256 `json:"preview_hash"`

	// Receipt corresponds to the JSON schema field "receipt".
	Receipt Receipt `json:"receipt"`

	// Revision corresponds to the JSON schema field "revision".
	Revision int `json:"revision"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion WorkflowAdmissionSchemaVersion `json:"schema_version"`

	// Workflow corresponds to the JSON schema field "workflow".
	Workflow WorkflowDefinition `json:"workflow"`
}

type WorkflowAdmissionKind string

const WorkflowAdmissionKindWorkflowAdmission WorkflowAdmissionKind = "workflow_admission"

type WorkflowAdmissionPreview struct {
	// Actor corresponds to the JSON schema field "actor".
	Actor string `json:"actor"`

	// BaseRevision corresponds to the JSON schema field "base_revision".
	BaseRevision int `json:"base_revision"`

	// Campaign corresponds to the JSON schema field "campaign".
	Campaign CampaignDefinition `json:"campaign"`

	// CampaignHash corresponds to the JSON schema field "campaign_hash".
	CampaignHash SHA256 `json:"campaign_hash"`

	// CatalogHash corresponds to the JSON schema field "catalog_hash".
	CatalogHash SHA256 `json:"catalog_hash"`

	// CommitToken corresponds to the JSON schema field "commit_token".
	CommitToken SHA256 `json:"commit_token"`

	// CompileHash corresponds to the JSON schema field "compile_hash".
	CompileHash SHA256 `json:"compile_hash"`

	// DefinitionHash corresponds to the JSON schema field "definition_hash".
	DefinitionHash SHA256 `json:"definition_hash"`

	// ExpandedNodes corresponds to the JSON schema field "expanded_nodes".
	ExpandedNodes []ExpandedNodeContract `json:"expanded_nodes"`

	// Job corresponds to the JSON schema field "job".
	Job JobDefinition `json:"job"`

	// JobHash corresponds to the JSON schema field "job_hash".
	JobHash SHA256 `json:"job_hash"`

	// Kind corresponds to the JSON schema field "kind".
	Kind WorkflowAdmissionPreviewKind `json:"kind"`

	// PreviewHash corresponds to the JSON schema field "preview_hash".
	PreviewHash SHA256 `json:"preview_hash"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion WorkflowAdmissionPreviewSchemaVersion `json:"schema_version"`

	// Workflow corresponds to the JSON schema field "workflow".
	Workflow WorkflowDefinition `json:"workflow"`
}

type WorkflowAdmissionPreviewKind string

const WorkflowAdmissionPreviewKindWorkflowAdmissionPreview WorkflowAdmissionPreviewKind = "workflow_admission_preview"

type WorkflowAdmissionPreviewSchemaVersion int

type WorkflowAdmissionSchemaVersion int

type WorkflowDefinition struct {
	// Blockers corresponds to the JSON schema field "blockers".
	Blockers Strings `json:"blockers"`

	// Completion corresponds to the JSON schema field "completion".
	Completion NonEmptyStrings `json:"completion"`

	// DefaultContext corresponds to the JSON schema field "default_context".
	DefaultContext []ContextRequirement `json:"default_context"`

	// DefinitionHash corresponds to the JSON schema field "definition_hash".
	DefinitionHash *SHA256 `json:"definition_hash,omitempty,omitzero"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id"`

	// Intent corresponds to the JSON schema field "intent".
	Intent IntentCard `json:"intent"`

	// Kind corresponds to the JSON schema field "kind".
	Kind WorkflowDefinitionKind `json:"kind"`

	// Nodes corresponds to the JSON schema field "nodes".
	Nodes []NodeDefinition `json:"nodes"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs []Slot `json:"outputs"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion WorkflowDefinitionSchemaVersion `json:"schema_version"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version"`
}

type WorkflowDefinitionKind string

const WorkflowDefinitionKindWorkflowDefinition WorkflowDefinitionKind = "workflow_definition"

type WorkflowDefinitionSchemaVersion int

type WorkflowLintIssue struct {
	// Code corresponds to the JSON schema field "code".
	Code Identifier `json:"code"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path"`

	// Severity corresponds to the JSON schema field "severity".
	Severity WorkflowLintIssueSeverity `json:"severity"`
}

type WorkflowLintIssueSeverity string

const WorkflowLintIssueSeverityError WorkflowLintIssueSeverity = "error"
const WorkflowLintIssueSeverityWarning WorkflowLintIssueSeverity = "warning"

type ReceiptPreviousReceiptHash_0 = SHA256

type WorkflowLintReport struct {
	// Issues corresponds to the JSON schema field "issues".
	Issues []WorkflowLintIssue `json:"issues"`

	// Kind corresponds to the JSON schema field "kind".
	Kind WorkflowLintReportKind `json:"kind"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion WorkflowLintReportSchemaVersion `json:"schema_version"`

	// Valid corresponds to the JSON schema field "valid".
	Valid bool `json:"valid"`
}

type WorkflowLintReportKind string

const WorkflowLintReportKindWorkflowLintReport WorkflowLintReportKind = "workflow_lint_report"

type WorkflowLintReportSchemaVersion int

type WorkflowRef string
